# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.cache/wt [current_project]
set_property parent.project_path D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/sources_1/new/prelucrare_cifra.vhd
  D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/sources_1/new/divizor_frecventa.vhd
  D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/sources_1/new/codificator.vhd
  D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/sources_1/new/anozi.vhd
  D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/sources_1/new/numarator_9999.vhd
  D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/sources_1/new/mouse_interface.vhd
  D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/sources_1/new/divizor_frecventa_numarator.vhd
  D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/sources_1/new/DISPLAY.vhd
  D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/sources_1/new/UE.vhd
  D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/sources_1/new/UC.vhd
  D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/sources_1/new/BLACK_BOX.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/constrs_1/new/constrangeri.xdc
set_property used_in_implementation false [get_files D:/SCOALA/FACULTATE/II/PSN/PROIECT/PROIECT/UC/UC.srcs/constrs_1/new/constrangeri.xdc]


synth_design -top BLACK_BOX -part xc7a35tcpg236-1


write_checkpoint -force -noxdef BLACK_BOX.dcp

catch { report_utilization -file BLACK_BOX_utilization_synth.rpt -pb BLACK_BOX_utilization_synth.pb }
